name: Aternos AFK Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        env:
          SERVER_IP: Kiingdom_SmP.aternos.me
          SERVER_PORT: "36463"
          BOT_NAME: ${{ secrets.GUARDIAN }}
        run: node index.js
